@startuml
struct Dimension {
    unsigned char width
    unsigned char height

    - Dimension* createDimension(const unsigned char width, const unsigned char height)
    - void deleteDimension(Dimension* dimension)
}

stereotype Constraint {
    unsigned char adjacentBlack
}

struct ConstraintCell {
    Constraint constraint
    ConstraintCell* next

    - ConstraintCell* createConstraintCell(const Constraint constraint)
    - void deleteConstraintCell(ConstraintCell* constraintCell)
}

struct Constraints {
    ConstraintCell* head

    - Constraints* createConstraints()
    - void deleteConstraints(Constraints* constraints)
    - void ConstraintsAddConstraints(Constraints* contraints, const Constraint constraint)
    - unsigned char constraintsGetSize(const Constraints* constraints)
    - unsigned char* constraintsToArray(const Constraints* constraints)
}

enum Pixel {
    BLACK
    WHITE
}

struct Grid {
    Pixel** pixels

    - Grid createGrid(const Dimension* dimension)
    - void deleteGrid(Grid grid, const Dimension* dimension)
    - void gridToggleXY(Grid grid, const unsigned char x, const unsigned char y, const Dimension* dimension)
    - Pixel gridGetXY(Grid grid, const unsigned char x, const unsigned char y, const Dimension* dimension)
}

struct Nonogram {
    Dimension* dimension
    Grid grid
    Constraints** rowConstraints
    Constraints** columnConstraints

    + Nonogram* createNonogram(const unsigned char width, const unsigned char height)
    + void deleteNonogram(Nonogram* nonogram)
    + void nonogramAddRowConstraint(const Nonogram* nonogram, const unsigned char rowIndex, const Constraint constraint)
    + void nonogramAddColumnConstraint(const Nonogram* nonogram, const unsigned char columnIndex, const Constraint constraint)
    + unsigned char nonogramGetWidth(const Nonogram* nonogram)
    + unsigned char nonogramGetHeight(const Nonogram* nonogram)
    + void nonogramToggleXY(const Nonogram* nonogram, const unsigned char x, const unsigned char y)
    + Pixel nonogramGetXY(const Nonogram* nonogram, const unsigned char x, const unsigned char y)
    + unsigned char nonogramRowsConstraintsGetSize(const Nonogram* nonogram, const unsigned char rowIndex)
    + unsigned char nonogramColumnsConstraintsGetSize(const Nonogram* nonogram, const unsigned char columnIndex)
    + unsigned char* nonogramRowsConstraintsToArray(const Nonogram* nonogram, const unsigned char rowIndex)
    + unsigned char* nonogramColumnsConstraintsToArray(const Nonogram* nonogram, const unsigned char columnIndex)
}

Nonogram *--> Dimension
Nonogram o--> "2" Constraints
Nonogram *--> Grid

Constraints o--> ConstraintCell

ConstraintCell *--> Constraint
ConstraintCell o--> ConstraintCell

Grid *--> "width*height" Pixel
@enduml